version: 2
jobs:
  macOStest:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: bundle install      
      - run:
          name: Run Tests
          command: |
              swift test --enable-code-coverage 2>&1 |
              xcpretty --report html --output test_output/results.html --report junit --output test_output/unit-tests/results.xml
      - run:
          name: Generate xcode project for code coverage
          command: |
              swift package generate-xcodeproj
      - run:
          name: Post Coverage
          command: bundle exec slather              
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output/results.html
workflows:
  version: 2
  run-tests:
    jobs:
      - macOStest

