name: Test

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.configurations.destination }}
    runs-on: macOS-13
    strategy:
      matrix:
        configurations:
          - destination: "platform=macOS"
            scheme: "Fetch-macOS"
            platform: "macOS"
    
    steps:
    - name: Xcode Select
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

    - name: Checkout
      uses: actions/checkout@v4

    - name: Bundler
      run: bundle install

    - name: Generate xcode project for code coverage
      run: swift package generate-xcodeproj --enable-code-coverage

    - name: Run tests on ${{ matrix.configurations.destination }}
      run: xcodebuild -scheme Config-Package test |
           xcpretty --report html --output test_output/results.html --report junit --output test_output/unit-tests/results.xml

    - name: Post Coverage
      run: bundle exec slather
