name: Test

on: [push]

jobs:
  test:
    name: Test on destination macOS
    runs-on: macOS-13
    
    steps:
    - name: Xcode Select
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: swift test --enable-code-coverage

